apiVersion: apps/v1
kind: Deployment
metadata:
  name: samiapp2
  labels:
    app: samiapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samiapp2
  template:
    metadata:
      labels:
        app: samiapp2
    spec:
      containers:
      - name: samiapp2
        image: satak/samiapp2:latest
        ports:
        - containerPort: 8080
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
