apiVersion: apps/v1
kind: Deployment
metadata:
  name: $appName
  labels:
    app: $appName
    version: $appVersion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $appName
  template:
    metadata:
      labels:
        app: $appName
        version: $appVersion
    spec:
      containers:
      - name: $appName
        image: $($repository)/$($appName):$version
        ports:
        - containerPort: 8080
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
